package com.layla.items;

/** Identifier for each passive item. */
public enum ItemId {
    SWIFT_BOOTS,
    GLASS_CANNON,
    TEARS_UP,
    RANGE_UP,
    SHOT_SPEED_UP,

    // NUEVOS ÍTEMS
    TRIPLE_SHOT,
    QUAD_SHOT,
    CUPIDS_ARROW,  // Pierce
    RUBBER_CEMENT, // Bounce
    SPOON_BENDER,  // Homing

    BANDAGE,
    SMALL_CHESTPLATE,
    RUNNING_SHOES,
    PROTEIN_BAR,
    DUCT_TAPE,
    LIGHT_BOOTS,
    ENERGY_DRINK,
    BROKEN_BULLET,
    SHARP_ROCK,
    PRACTICE_TARGET,
    METAL_SCRAP,
    RUSTY_SPRING,
    PEASHOOTER_AMMO,
    HARDENED_TIP,
    PIGGY_BANK,
    LUCKY_CHARM,
    MAGNET,
    COUPON,
    COIN_BAG,
    SCRAP_METAL,

    IRON_PLATE,
    MEDKIT,
    REINFORCED_BOOTS,
    NANO_SHIELD,
    MEGA_HEART,
    EXPLOSIVE_ROUNDS,
    PRECISION_SCOPE,
    SPIKED_GLOVES,
    DUAL_SPRINGS,
    BOUNCING_GEL,
    TEFLON_AMMO,
    CRITICAL_EYE,
    GOLDEN_WALLET,
    LUCKY_DICE,
    BIG_MAGNET,
    VOUCHER,
    LUCKY_COIN,
    SHOP_SCANNER,

    REACTOR_CORE,
    ADRENALINE_PUMP,
    BIO_STEEL_SKIN,
    GENETIC_UPGRADE,
    SNIPER_MODULE,
    BALLISTIC_CPU,
    PLASMA_ROUNDS,
    RICOCHET_CORE,
    DRILL_BIT,
    GOLDEN_MIND,
    CHAOS_ENGINE,
    TITAN_BLOOD
}
